### ISSUE TITLE
Use `_jll` Geant4

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/Geant4.jl#1]
instead of `cvmfs`, maybe use jll which was built: https://github.com/JuliaPackaging/Yggdrasil/tree/master/G/Geant4

should work depending on what you need exactly, at some point we added `X11` into it to support more stuff, but if something's missing maybe we can try to add more.

**Comment by peremato** [comment]
Yes, but wanted to worry about packing the binaries  after I have convinced myself that the generated wrappers with wrapit does something useful.  Good to know.

**Comment by oschulz** [comment]
Wow, I didn't realize we had Geant4 binaries in Yggdrasil already!

Also, @peremato , thanks a lot for this initiative!
