### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by oschulz** [JuliaHEP/Geant4.jl#2]
@peremato , when this package gets registered, Julia Registrator won't like the fact that it's already at version 0.1.2.

I would suggest to revert to version 0.1.0, if possible, until package registration.

CC @moelf

**Comment by peremato** [comment]
I increased the version number on my failed attempts to register. It required Geant4_julia_jll be registered and some issue with the compat section. According to the mail I got I should re-attempt without changing the version.

**Comment by oschulz** [comment]
> I increased the version number on my failed attempts to register.

Yes, you don't need to increase the version number to re-try registering, you can just comment `<@-sign>JuliaRegistrator register` on a different commit to re-trigger registration. Also, ideally, don't create the tags/releases by hand, but use the [Julia TagBot](https://github.com/JuliaRegistries/TagBot), it'll create the tags and releases for you. That will ensure that the tags/releases on the repo match the package versions in the Registry.

**Comment by peremato** [comment]
@oschulz  Before re-trying the registration I need to sort out the problem https://github.com/JuliaRegistries/General/pull/80960#issuecomment-1495267235 registering `Geant4_julia_jll` I have asked Mosè Giordano, but  perhaps you have an idea. https://github.com/JuliaPackaging/Yggdrasil/pull/6490#issuecomment-1495388772

**Comment by oschulz** [comment]
Regarding the name "geant4_julia_jll",

write a comment like

```
[noblock]

Regarding "Lowercase package name geant4_julia_jll contains the string julia"  - I tried to follow naming conventions for similar packages in Yggdrasil". Could this be merged manually?
```

on https://github.com/JuliaRegistries/General/pull/80960 .

But like you say, the package loading problem needs to be figured out first. @giordano is the expert here ... 
Mosè, do you see what's going wrong there?

**Comment by giordano** [comment]
I answered at https://github.com/JuliaPackaging/Yggdrasil/pull/6490#issuecomment-1495715943

**Comment by peremato** [comment]
The registration did work successfully.

**Comment by oschulz** [comment]
Congrats!

**Comment by oschulz** [comment]
I suggest you add [Julia TagBot](https://github.com/marketplace/actions/julia-tagbot) to your GitHub actions, @peremato , it'll automatically created releases on the repo after Registrator is done with it's job.

**Comment by oschulz** [comment]
I also very highly recommend to add https://github.com/JuliaRegistries/CompatHelper.jl as a GitHub action.
