### ISSUE TITLE
Using `G4BooleanSolids` in Geant4.jl

### ISSUE THREAD

**Issue by fhagemann** [JuliaHEP/Geant4.jl#5]
Hi and first of all: thanks for the initiative of including Geant4.jl within Julia!

I was playing around a bit with the package with the major goal to implement MC capabilities for detector simulations in [SolidStateDetectors.jl](https://github.com/JuliaPhysics/SolidStateDetectors.jl) that is also based on GEANT4-like constructive solid geometry.

While trying to translate our geometries, it seems like basic primitives like Boxes, Tubes, Spheres, etc. are already implemented but the boolean operators (`G4BooleanSolid`) like `G4UnionSolid`, `G4SubtractionSolid` and `G4IntersectionSolid` seem to be not defined yet.

What would need to be the steps to have the boolean solids supported by Geant4.jl as well?

**Comment by peremato** [comment]
Thanks for trying. I am about to release/register a new version with some more functionality (scoring) , but not the boolean shapes yet. The idea is to add the missing pieces, but I was hold back by the time it takes to compile the generated CxxWrap code (which is generated in a single heavy templated file). I have made progress on this and soon I think I can add more classes.
Meanwhile, what should be working is to input the geometry with a GDML file. Have you try it?

**Comment by fhagemann** [comment]
Thanks for the prompt response!
Is there a way to pass GDML content to Geant4.jl in memory without having to write a temporary file?

**Comment by peremato** [comment]
No, it is using the native Geant4 interface and requires a real file to parse. You can create a temporary file...
It is done like this: https://github.com/JuliaHEP/Geant4.jl/blob/5157afa957fb742f6b2abb5e0c6870aff839edd9/examples/TestEm3/TestEm3-gdml.jl#L177

**Comment by fhagemann** [comment]
Thanks so much for input, I'll try it out!

**Comment by peremato** [comment]
The latest version 0.1.6 has  the wrappers to the `G4BooleanSolids`. See the notebook with their graphical representation. https://juliahep.github.io/Geant4.jl/stable/notebooks/Solids/ 
I am closing  the issue. If  you have problems do not doubt to report them.
